### ISSUE TITLE
Error when i start

### ISSUE THREAD

**Issue by cruxm4n** [Kla35/lis-generator#10]
https://prnt.sc/vuuzhm

When  i start i have this error :/

**Comment by Kla35** [comment]
Strange, I never had this issue, it seems like the canvas module doesn't work, I'm gonna check that today for sure

**Comment by Kla35** [comment]
@cruxm4n It seems like the error isn't from my code, but from Node.js compilation. https://stackoverflow.com/questions/13035760/node-js-native-module-is-not-a-valid-win32-application-error
I'm gonna see what's wrong more deeply later in the day

**Comment by Kla35** [comment]
@cruxm4n I update the canvas module with https://github.com/Kla35/lol-picture-generate-for-stream/commit/1bb99587ca39a8835bbe99d387210b156208ab1e, maybe it works now, do a git pull and test :/
But it's seems to be not from my code, but from ur Windows version (x32)
