### ISSUE TITLE
Software freezes on Researching Game

### ISSUE THREAD

**Issue by truestcanadian** [Kla35/lis-generator#12]
After inserting the needed API and match information, the program seems to infinitely stay stuck on Researching Game.

**Comment by Kla35** [comment]
Hello @truestcanadian !
After trying on my computer, it works perfectly
![example](https://user-images.githubusercontent.com/37518897/111854777-623ca600-8921-11eb-9d88-44efc5261780.png)
 !
Can u send a screenshot of the error ? Plus the configuration of ur PC ?

**Comment by ChronoBrake** [comment]
same error
![errorlis](https://user-images.githubusercontent.com/47286873/111917264-5cf56d80-8a7f-11eb-8781-a07349f18f61.PNG)

**Comment by Kla35** [comment]
Hello,
Okay, I've got a idea of what doesn't work.
Basically, it seems like the dependencies doesn't extract well when I create the executable
I'm gonna check that and release a new version, thanks for ur feedback!

**Comment by Kla35** [comment]
While I was investigating, it seems like the .gitignore ignored the node_modules folder, so the node_modules wasn't updated for a while. The issue seems to come from that.
I'm gonna upload this right now, and ping u when u will be able to pull

**Comment by Kla35** [comment]
@ChronoBrake With commit https://github.com/Kla35/lis-generator/commit/bda55a192623f29f16e8aed73156498479a74f91 , I think it should be okay rn, can u retry and send me a screenshot if it doesn't work ?

**Comment by ChronoBrake** [comment]
now, working fine

**Comment by Kla35** [comment]
Nice ! Don't hesitate to open a new issue if u still have some trouble !
