### ISSUE TITLE
[Question] How get easily the match id  ? 

### ISSUE THREAD

**Issue by cruxm4n** [Kla35/lis-generator#14]
After watching a game, how can you easily get the match id by saying that you don't have access to the link: visit the web?

**Comment by Kla35** [comment]
Hey @cruxm4n,
If u can't access to the link by using the match history, u can use website like [LeagueOfGraphs](https://www.leagueofgraphs.com/), who display the match id in the url.
Search your username in game, and clic on a game on the profile
For example, for my last draft game : 
![exampleLeague](https://user-images.githubusercontent.com/37518897/112722225-7af02180-8f08-11eb-889d-d557e4a1f87b.png)

**Comment by cruxm4n** [comment]
And for the custom game is it impossible to have it?

**Comment by Kla35** [comment]
While it's very hard to get the match id of a custom game, the issue isn't here.
To be clear : Riot API doesn't allow to access to data on a custom game. The only solution I found is to connect my program to League of Legends client. At the end of the game, u have a endpoint to fetch some stats on the game.
Unfortunately, these data aren't complete. U can't know how many drakes has been killed in the game, u can't know how many barons has been killed in the game, u don't have the graph diff per minute.
I tried in the past to make a version of this program for custom game, and I success but... It's not very stable unless u know exactly how it works.
U have to enter the drake kill by urself etc... I send a message to Riot Devs, but I still don't have a answer rn

**Comment by Kla35** [comment]
There is the v2.0 of my program, who include the endpoint to get the postgame image of a custom game
![image](https://user-images.githubusercontent.com/37518897/112722819-e5569100-8f0b-11eb-876f-3c644d881790.png)
As u can see, it's not really intuitive
But, even if u can't get the postgame image, u can still generate the pre game image by using the username of someone in the custom game (while players are in game).

**Comment by cruxm4n** [comment]
Do you have discord ?
