### ISSUE TITLE
Problem generating post game from custom game

### ISSUE THREAD

**Issue by ramang22** [Kla35/lis-generator#15]
Hi, today I tried to generate post game imagine from custom game. Game id = 2791568216. But its stuck into prepare data for generation. Ranked games/flexq works fine.
![image](https://user-images.githubusercontent.com/29985921/113909313-d5766100-97d7-11eb-9633-9a79c0c21245.png)

Ty for help

**Comment by Kla35** [comment]
Hello @ramang22 ,
As I said previously in [issue#14](https://github.com/Kla35/lis-generator/issues/14), it's not possible to used my software on custom game, except if u played a match with tournament code.
Riot doesn't allow us to retrieve data from custom game, and we don't know why.
While Riot doesn't allow that, my software will not handle this issue, I'm sry :/
