### ISSUE TITLE
I am from China in Asia. How can I use this software?

### ISSUE THREAD

**Issue by JIANYU77I** [Kla35/lis-generator#16]
I downloaded the software, entered my GAME ID and competition name, filled in the API key, and then set up a custom room. The server chose the first one. Because there was no China, the [software](url) prompt kept turning, so I could not use the Research GAME

**Comment by JIANYU77I** [comment]
![屏幕截图 2021-04-21 180621](https://user-images.githubusercontent.com/82941693/115536532-7a129b80-a2cc-11eb-8e4b-4e88506a153a.png)

**Comment by Kla35** [comment]
Hello,
Unfortunately, China server are not accessible from Riot API, due to country restriction.
So, it's impossible to use my software on China, sorry :/

**Comment by JIANYU77I** [comment]
Hi, I'm sorry about that, but I have an idea, can we just access the local client to get the custom race runes, loading screen and post-race data, we as OB, or Observers
















At 2021-04-21 20:35:54, "Kla35" ***@***.***> wrote:

Hello,
Unfortunately, China server are not accessible from Riot API, due to country restriction.
So, it's impossible to use my software on China, sorry :/
