### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by ChronoBrake** [Kla35/lis-generator#17]
Hey, first of all thanks for that project. Your work be awesome!

Project will have any updates? I can see in other branch incomplete some really nice feature like MVP.

Best Regards

**Comment by Kla35** [comment]
Hey, thank u for ur message :)

At this point, the software works on the initial branch
The others branchs available are some tests and enhancements I tried to do.
Unfortunately, consider this project stopped for the moment. Indeed, Riot Games doesn't give in a easy way all the data I need to make enhancement
To explain : A lot of these data can be get by client (LCU), but in a very hard and specific way

The branch "ga" was created with a MVP feature for example, but it was only used on a LAN, where some specific conditions allows me to had access to all the data I need. On live server, it's not the case unfortunately D:

If the software doesn't work anymore, I'm able to patch it and maintain it. But it will not be enhanced while Riot Games doesn't give more infos on games, and especially on custom games :/ Sry about that
