### ISSUE TITLE
Match V4 deprecated, needs update

### ISSUE THREAD

**Issue by ChronoBrake** [Kla35/lis-generator#20]
Hey Sir,

Match V4 not working anymore, you will update your awesome tool to new version V5?
Regards

**Comment by Kla35** [comment]
Hey @ChronoBrake ,

I didn't know my tool was used by people ahah
I can't promise, but I can check this evening !

**Comment by Kla35** [comment]
I just look at the new API Match v5, and they make a reworking of the API, so it means that I have to take time to make changes.
Seems like the new API is close to TFT API, so I'm used with it, but I need to recatch all the infos from League Game
Not seems impossible, but I will take me some time while I'm now a full time student
For when do u need it ?

**Comment by Kla35** [comment]
@ChronoBrake Hey, I take a moment, and.......... it seems to be more easier than I thought !
I don't know when it will be up, but it won't take a lot of time !

**Comment by Kla35** [comment]
Up @ChronoBrake 
I'm glad to say that my app is now working with Match V5 ! :D Commit : https://github.com/Kla35/lis-generator/commit/91186ba3f250c2b196843209410e2d57612bdf29
Seems we have more data than earlier, I'm thinking about adding a MVP picture...
I also ajust dmg chart, to make the two team dmg chart with the biggest dmg in the game

A new change too : Before, when u put the match id, it was only the match id.
Now, u have to put the server where the game was played. I'm gonna see if I can work on this later.
Check example below : 
Old match id : 469902960
New match id : **EUW1_**5469902960 

/!\ WARNING : As before, this app won't generate postgame on custom game, for the reason that Riot doesn't save data from custom game /!\

EDIT : I've just updated the repo, I didn't update the executable right now, I'll do that tomorrow

**Comment by OrionCodeDev** [comment]
Okey i i waiting for it <3

**Comment by Kla35** [comment]
The 1.2.9 version is now out !
Still a issue in using the username atm, I'm gonna fix it ASAP

**Comment by OrionCodeDev** [comment]
Yeah it's working also MVP function will be awesome <3

**Comment by Kla35** [comment]
@ChronoBrake As I asked before, for what usage do u use this soft ?
I'm just curious about that haha

For the MVP function, I got some ideas to do that, it doesn't seems hard to do, but I have less time now to developp my own software
I can't tell u when it will be integrated, sry D:

**Comment by OrionCodeDev** [comment]
Hey latest version giving error when i run it by "npm start". What's the problem? Regards
```
`> lol-runes-pregame@1.0.0 start
> electron .

node:internal/child_process:415
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at Object.spawn (node:child_process:698:9)
    at Object.<anonymous> (C:\Users\yoube\Desktop\lis-generator-master\node_modules\electron\cli.js:7:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}`
```

**Comment by Kla35** [comment]
I'm pretty surprised 'cause the soft worked for me, even if only sources files.
I've searching a bit on Internet and I find out that the soft won't work because u're not running it from a administrator session, I will check that later

**Comment by OrionCodeDev** [comment]
I think the problem is with node_modules and not updated package.json. You can upload your full git version with modules and updated package.json?
